import { createGlobalThemeContract } from '@vanilla-extract/css';

export const theme = createGlobalThemeContract(
  {
    font: {
      jp: null,
      roboto: null,
    },
    fontSize: {
      xxxs: null,
      xxs: null,
      xs: null,
      s: null,
      m: null,
      l: null,
      xl: null,
      xxl: null,
      xxxl: null,
    },
    lineHeight: {
      flat: null,
      tight: null,
      normal: null,
      wide: null,
    },
    space: {
      '0': 'space-0',
      '0.5': 'space-50',
      '1': 'space-100',
      '1.5': 'space-150',
      '2': 'space-200',
      '2.5': 'space-250',
      '3': 'space-300',
      '4': 'space-400',
      '5': 'space-500',
      '6': 'space-600',
      '7': 'space-700',
      '8': 'space-800',
      '9': 'space-900',
      '10': 'space-1000',
      '12': 'space-1200',
      '16': 'space-1600',
      '20': 'space-2000',
      '24': 'space-2400',
      '28': 'space-2800',
      '32': 'space-3200',
    },
    radius: {
      xs: null,
      s: null,
      m: null,
      l: null,
      xl: null,
      xxl: null,
      full: null,
    },
    palette: {
      neutral: {
        10: null,
        20: null,
        30: null,
        40: null,
        50: null,
        60: null,
        70: null,
        80: null,
        90: null,
        100: null,
        white: null,
        black: null,
      },
      blue: {
        10: null,
        20: null,
        30: null,
        40: null,
        50: null,
        60: null,
        70: null,
        80: null,
        90: null,
        100: null,
      },
    },
    color: {
      text: {
        default: null,
        subdued: null,
        white: null,
      },
      background: {
        default: null,
        card: null,
      },
      primary: {
        default: null,
        hover: null,
      },
      border: {
        default: null,
      },
    },
  },
  (value, path) => `--theme-${value || path.join('-')}`,
);